/**
 * YouTube API 클라이언트 타입 정의
 *
 * YouTube Data API v3 응답 타입과 클라이언트 함수를 정의합니다.
 */

import { apiClient } from './client';

// ============================================================================
// YouTube API 응답 타입
// ============================================================================

/**
 * YouTube 영상 기본 정보
 */
export interface YouTubeVideo {
  id: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  channelId: string;
  channelTitle: string;
  publishedAt: string;
  duration: number; // 초 단위
  viewCount: number;
  likeCount: number;
  commentCount: number;
  tags?: string[];
  categoryId?: string;
  isShorts: boolean; // 60초 이하 여부
}

/**
 * YouTube 채널 정보
 */
export interface YouTubeChannel {
  id: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  subscriberCount: number;
  videoCount: number;
  viewCount: number;
  customUrl?: string;
}

/**
 * 검색 필터 옵션
 */
export interface YouTubeSearchFilters {
  videoType?: 'shorts' | 'long' | 'all'; // 쇼츠/롱폼/전체
  publishedAfter?: string; // ISO 8601 format
  publishedBefore?: string; // ISO 8601 format
  regionCode?: string; // KR, JP, US 등
  minViewCount?: number;
  maxViewCount?: number;
  minSubscribers?: number;
  maxSubscribers?: number;
  minCiiScore?: number; // Channel Influence Index
  maxCiiScore?: number;
  order?: 'relevance' | 'date' | 'viewCount' | 'rating' | 'cii';
}

/**
 * 검색 요청 파라미터
 */
export interface YouTubeSearchParams {
  query: string;
  maxResults?: number; // 25~50
  filters?: YouTubeSearchFilters;
  pageToken?: string; // 페이지네이션용
}

/**
 * 검색 결과
 */
export interface YouTubeSearchResult {
  videos: YouTubeVideo[];
  nextPageToken?: string;
  totalResults: number;
}

/**
 * 자막 트랙 정보
 */
export interface CaptionTrack {
  language: string;
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

/**
 * 자막 데이터
 */
export interface CaptionData {
  language: string;
  captions: CaptionSegment[];
}

/**
 * 자막 세그먼트
 */
export interface CaptionSegment {
  start: number; // 시작 시간 (초)
  duration: number; // 지속 시간 (초)
  text: string;
}

/**
 * CII (Channel Influence Index) 점수
 */
export interface CIIMetrics {
  channelId: string;
  score: number; // 0-100
  subscriberScore: number;
  viewCountScore: number;
  uploadFrequencyScore: number;
  engagementScore: number;
  calculatedAt: string;
}

// ============================================================================
// API 클라이언트 함수
// ============================================================================

/**
 * YouTube 영상 검색
 */
export async function searchVideos(
  params: YouTubeSearchParams
): Promise<YouTubeSearchResult> {
  const response = await apiClient.get('/api/v1/youtube/search', {
    params: {
      query: params.query,
      max_results: params.maxResults || 25,
      page_token: params.pageToken,
      ...params.filters,
    },
  });
  return response.data;
}

/**
 * 영상 상세 정보 조회
 */
export async function getVideoDetails(videoId: string): Promise<YouTubeVideo> {
  const response = await apiClient.get(`/api/v1/youtube/videos/${videoId}`);
  return response.data;
}

/**
 * 영상 자막 목록 조회
 */
export async function getCaptionTracks(
  videoId: string
): Promise<CaptionTrack[]> {
  const response = await apiClient.get(
    `/api/v1/youtube/videos/${videoId}/captions`
  );
  return response.data;
}

/**
 * 특정 언어 자막 다운로드
 */
export async function downloadCaption(
  videoId: string,
  language: string
): Promise<CaptionData> {
  const response = await apiClient.get(
    `/api/v1/youtube/videos/${videoId}/captions/${language}`
  );
  return response.data;
}

/**
 * 채널 CII 점수 조회
 */
export async function getChannelCII(channelId: string): Promise<CIIMetrics> {
  const response = await apiClient.get(
    `/api/v1/youtube/channels/${channelId}/cii`
  );
  return response.data;
}

/**
 * 검색 히스토리 조회
 */
export async function getSearchHistory(): Promise<string[]> {
  const response = await apiClient.get('/api/v1/youtube/search-history');
  return response.data;
}

/**
 * 검색 히스토리 저장
 */
export async function saveSearchHistory(keyword: string): Promise<void> {
  await apiClient.post('/api/v1/youtube/search-history', { keyword });
}

/**
 * 검색 히스토리 삭제
 */
export async function deleteSearchHistory(keyword: string): Promise<void> {
  await apiClient.delete(`/api/v1/youtube/search-history/${keyword}`);
}
